# Generated by Django 4.1.5 on 2023-02-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_remove_profile_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='history', to='app_users.history', verbose_name='История заказов'),
        ),
    ]
