# Generated by Django 4.1.5 on 2023-02-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_profile_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Кол-во продуктов в корзине',
            field=models.IntegerField(default=0),
        ),
    ]
