# Generated by Django 4.1.5 on 2023-02-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_profile_кол-во продуктов в корзине'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id истории для повторной оплаты',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Кол-во продуктов в корзине',
        ),
    ]
