# Generated by Django 4.1.5 on 2023-02-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_price', models.FloatField(default=0, verbose_name='минимальная цена в категории')),
                ('image', models.ImageField(upload_to='prod/', verbose_name='Иконка категории')),
                ('name', models.CharField(max_length=128, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название характеристики')),
                ('value', models.CharField(max_length=512, verbose_name='Значение характеристики')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=512, verbose_name='Имя комментатора')),
                ('avatar', models.ImageField(blank=True, upload_to='files/', verbose_name='Аватарка')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации отзыва')),
                ('text', models.CharField(max_length=4096, verbose_name='Текст отзыва')),
            ],
        ),
        migrations.CreateModel(
            name='Tegs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название тега')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Название товара')),
                ('photo', models.ImageField(upload_to='prod/', verbose_name='Аватарка')),
                ('description', models.CharField(max_length=1024, verbose_name='Описание товара')),
                ('price', models.FloatField(verbose_name='Цена товара')),
                ('manufacturer', models.CharField(max_length=256, verbose_name='Производитель')),
                ('limited_edition', models.BooleanField(default=False, verbose_name='Эксклюзивность товара')),
                ('reviews_count', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0, verbose_name='Счетчик проданных товаров')),
                ('category', models.ManyToManyField(to='app_shop.category', verbose_name='Категории')),
                ('characteristics', models.ManyToManyField(related_name='char', to='app_shop.characteristic', verbose_name='Характеристики')),
                ('reviews', models.ManyToManyField(blank=True, related_name='reviews', to='app_shop.reviews', verbose_name='Отзывы')),
                ('tegs', models.ManyToManyField(related_name='tegs', to='app_shop.tegs', verbose_name='Тэги')),
            ],
        ),
    ]
